name: std_uri_template
version: 0.0.1
description: A Dart implementation of URI Templates (RFC 6570).
issue_tracker: https://github.com/std-uritemplate/std-uritemplate/issues
repository: https://github.com/std-uritemplate/std-uritemplate

topics:
  - uri
  - template
  - rfc6570
  - std-uritemplate

environment:
  sdk: ^3.0.0
