name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - java
          - python
          - typescript
          - go
          - csharp
          - ruby
          - php
          - swift
        include:
          - php-version: '7.4'
          - php-version: '7.4'
            language: php
          - php-version: '8.2'
            language: php
    steps:
      - name: Common - Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      # Language specific setup

      # Java setup
      - name: Java - Set up JDK 11
        if: matrix.language == 'java'
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Java - Install jbang
        if: matrix.language == 'java'
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          echo "$HOME/.jbang/bin" >> $GITHUB_PATH

      # Python setup
      - name: Python - Install Poetry
        if: matrix.language == 'python'
        uses: snok/install-poetry@v1
      - name: Python - Add Poetry to PATH
        if: matrix.language == 'python'
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Typescript setup
      - name: Typescript - Setup Node
        uses: actions/setup-node@v3
        if: matrix.language == 'typescript'
        with:
          node-version: 18
      
      # Go setup
      - name: Go - Setup Go
        uses: actions/setup-go@v4
        if: matrix.language == 'go'
        with:
          go-version: '1.20'

      # C# setup
      - name: C# - Setup .NET
        uses: actions/setup-dotnet@v3
        if: matrix.language == 'csharp'
        with:
          dotnet-version: 7

      # Ruby setup
      - name: Ruby - Setup Ruby
        uses: ruby/setup-ruby@v1
        if: matrix.language == 'ruby'
        with:
          ruby-version: '3.0'

      # PHP setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        if: matrix.language == 'php'
        with:
          php-version: ${{ matrix.php-version }}

      # Swift setup
      - uses: swift-actions/setup-swift@v1
        if: matrix.language == 'swift'
        with:
          swift-version: "5.8"

      # Common testing
      - name: Common - Run Tests for ${{ matrix.language }}
        run: ./tests/test.sh ${{ matrix.language }}
